project:
  title: "Ortege"
  type: website
  output-dir: docs

format:
  html:
    theme: lumen

website:
  favicon: /images/favicon.png
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Products"
        menu:
          - text: "Ortege Studio"
            file: studio.qmd
          - text: "OrtegeGPT"
            file: ortegegpt.qmd
          - text: "Ortege Lakehouse"
            file: lakehouse.qmd
          - text: "Ortege Research"
            file: research.qmd
      