project:
  title: "docs"
  type: website
  output-dir: docs
format:
  html:
    theme: lumen
website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - studio.qmd 
      - ortegegpt.qmd
      - research.qmd
      - testnet_partner.qmd