project:
  title: "Ortege"
  type: website
  output-dir: docs

format:
  html:
    css: styles/custom-style.css
#    theme: lumen

website:
  favicon: /images/favicon.png
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Ortege Studio"
        menu:
          - text: "Overview"
            file: content/studio/overview.qmd
          - text: "Dashboards"
            file: content/studio/dashboards.qmd
          - text: "Charts"
            file: content/studio/charts.qmd
          - text: "Datasets"
            file: content/studio/datasets.qmd
          - text: "SQL LAB"
            file: content/studio/sqllab.qmd
          - text: "Database Connections"
            file: content/studio/dbconnections.qmd
      - text: "Ortege Lakehouse"
        menu:
          - text: "Overview"
            file: content/lakehouse/overview.qmd
          - text: "Bronze Layer"
            file: content/lakehouse/bronze.qmd
          - text: "Silver Layer"
            file: content/lakehouse/silver.qmd
          - text: "Gold Layer"
            file: content/lakehouse/gold.qmd
      - text: "OrtegeGPT"
        menu: 
          - text: "Overview"
            file: content/ortegegpt/overview.qmd
      