project:
  title: "Ortege"
  type: website
  output-dir: docs

format:
  html:
    css: styles/custom-style.css
    head-content: |
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-8H6E0MMTRH"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-8H6E0MMTRH', {
          'cookie_flags': 'SameSite=None;Secure'
        });
      </script>
#    theme: lumen

website:
  favicon: /images/favicon.png
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Ortege Studio"
        menu:
          - text: "Overview"
            file: content/studio/overview.qmd
          - text: "Dashboards"
            file: content/studio/dashboards.qmd
          - text: "Charts"
            file: content/studio/charts.qmd
          - text: "Datasets"
            file: content/studio/datasets.qmd
          - text: "SQL LAB"
            file: content/studio/sqllab.qmd
          - text: "Database Connections"
            file: content/studio/dbconnections.qmd
      - text: "Ortege Lakehouse"
        menu:
          - text: "Overview"
            file: content/lakehouse/overview.qmd
          - text: "Medallian Architecture"
            file: content/lakehouse/medallian.qmd
          - text: "API"
            file: content/lakehouse/api.qmd
      - text: "Datasets"
        menu: 
          - text: "Stacks"
            file: content/lakehouse/datasets/stacks.qmd
          - text: "Bitcoin"
            file: content/lakehouse/datasets/bitcoin.qmd
          - text: "Stellar"
            file: content/lakehouse/datasets/stellar.qmd
          - text: "Movement Labs"
            file: content/lakehouse/datasets/movement.qmd
          - text: "Pricing"
            file: content/lakehouse/datasets/pricing.qmd
          - text: "Address Book"
            file: content/lakehouse/datasets/address_book.qmd
      - text: "Ortege Notebooks"
        menu: 
          - text: "Overview"
            file: content/notebooks/overview.qmd
      - text: "OrtegeGPT"
        menu: 
          - text: "Overview"
            file: content/ortegegpt/overview.qmd
      