project:
  title: "docs"
  type: website
  output-dir: docs
nav:
  - title: "Home"
    href: index.qmd
  - title: "Quick Start"
    href: quick_start.qmd
  - title: "Data"
    href: data.qmd
  - title: "Ortege Studio"
    href: studio.qmd
  - title: "Research Articles"
    href: research.qmd
format:
  html:
    theme: lumen
website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - studio.qmd 
      - ortegegpt.qmd
      - research.qmd