---
title: "Data Ontology"
format:
  html:
    toc: true
    html-math-method: katex
    css: styles.css
---

# Chains supported

Initially we will go live with:

-   Bitcoin

-   Avalanche

-   Stacks

Followed by

-   Soroban (Stellar)

-   Movement Labs (Move based chains)

# Bitcoin

Bitcoin data follows a UTXO model. We expose two raw tables:

1.  Blocks
2.  Transactions

## Blocks

| Column name         | Column type | Description                                                                                                                               |
|---------------------|-------------|-------------------------------------------------------------------------------------------------------------------------------------------|
| bits                | varchar     | The difficulty threshold specified in block header                                                                                        |
| chainwork           |             | The expected number of hashes required to produce the current chain                                                                       |
| coinbase            | varchar     | The data specified in the coinbase transaction of the block                                                                               |
| hash                | varchar     | The block hash                                                                                                                            |
| merkle_root         | varchar     | The root node of a Merkle tree, where leaves are transaction hashes                                                                       |
| previous_block_hash |             | The hash of the previous block                                                                                                            |
| date                |             | The block date                                                                                                                            |
| difficulty          |             | The estimated amount of work done to find this block relative to the estimated amount of work done to find block 0                        |
| height              | bigint      | The block number                                                                                                                          |
| mint_reward         |             | The output paid out to the miner for minting the block                                                                                    |
| nonce               | varchar     | The number of transactions made by the sender prior to this one                                                                           |
| size                | bigint      | The size of the block                                                                                                                     |
| stripped_size       | bigint      | The size of the block excluding witness data                                                                                              |
| time                |             | The block time                                                                                                                            |
| total_fees          |             | The fees paid out to the miner from transaction users. Each transaction's fee is what's left of output after input is subtracted from it. |
| total_reward        |             | The static reward given to the miner. It is the sum of the outputs in the coinbase transaction (the first transaction).                   |
| transaction_count   | bigint      | The number of transactions in the block                                                                                                   |
| version             | bigint      |                                                                                                                                           |
| weight              | bigint      | The block weight as defined in [BIP 141](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki)                                  |

## Transactions

| Column name  | Type | Description                                                                                                                                  |
|--------------|------|----------------------------------------------------------------------------------------------------------------------------------------------|
| block_time   |      | The block time                                                                                                                               |
| block_date   |      | The block date                                                                                                                               |
| block_height |      | The block number                                                                                                                             |
| block_hash   |      | The hash of the block that contains this transaction                                                                                         |
| index        |      | The number of the transaction in the block.                                                                                                  |
| id           |      | The id (hash) of this transaction                                                                                                            |
| input_value  |      | Total value of inputs in the transaction                                                                                                     |
| output_value |      | Total value of outputs in the transaction                                                                                                    |
| fee          |      | The transaction fee paid to the miner. = output_value - input_value                                                                          |
| input_count  |      | The number of inputs in the transaction                                                                                                      |
| output_count |      | The number of outputs in the transaction                                                                                                     |
| size         |      | The size of this transaction in bytes                                                                                                        |
| virtual_size |      | The virtual transaction size (differs from size for witness transactions)                                                                    |
| is_coinbase  |      | The transaction is a coinbase transaction, which is the first transaction in a block                                                         |
| coinbase     |      | If the transaction is a coinbase transaction, contains the coinbase data. Otherwise, null.                                                   |
| inputs       |      | Transaction inputs                                                                                                                           |
| outputs      |      | Transaction outputs. See outputs table.                                                                                                      |
| lock_time    |      | Earliest time that miners can include the transaction in their hashing of the Merkle root to attach it in the latest block of the blockchain |
| hex          |      | The transaction encoded as hexadecimal                                                                                                       |

### Inputs

| Field            | Data type | Description                                                              |
|------------------|-----------|--------------------------------------------------------------------------|
| value            |           | The number of Satoshis attached to this output                           |
| height           |           | The height of the output                                                 |
| tx_id            |           | The transaction id of the output that is here used as input              |
| output_number    |           | The number (index) of the output in transaction `tx_id`'s outputs        |
| coinbase         |           | The data specified in this transaction, if it was a coinbase transaction |
| sequence         |           | Sequence number                                                          |
| witness_data     |           | Array of hex encoded witness data                                        |
| script_signature |           | The script signature                                                     |
| script_pub_key   |           | The script public key                                                    |

#### Script signature

| Field | Data type | Description                                                     |
|-------|-----------|-----------------------------------------------------------------|
| hex   |           | The transaction's script operations, in hex                     |
| asm   |           | The transaction's script operations, in symbolic representation |

#### Script public key

| Field   | Data type | Description                                                     |
|---------|-----------|-----------------------------------------------------------------|
| asm     |           | The transaction's script operations, in symbolic representation |
| desc    |           | The transaction's script operations, in symbolic representation |
| address |           | The transaction's script operations, in symbolic representation |
| hex     |           | The transaction's script operations, in hex                     |
| type    |           | The address type of the output                                  |

### Outputs

| Field          | Data type | Description                                                                                                     |
|----------------|-----------|-----------------------------------------------------------------------------------------------------------------|
| index          |           | 0-indexed number of an output within a transaction used by a later transaction to refer to that specific output |
| value          |           | The number of Satoshis attached to this output                                                                  |
| script_pub_key |           | The public key                                                                                                  |

#### Script public key

| Field   | Data type | Description                                                     |
|---------|-----------|-----------------------------------------------------------------|
| asm     |           | The transaction's script operations, in symbolic representation |
| hex     |           | The transaction's script operations, in hex                     |
| address |           | The address the BTC came from                                   |
| type    |           | The address type of the output                                  |

# Avalanche

## Blocks

| Column name        | Data type | Description                                                                              |
|--------------------|-----------|------------------------------------------------------------------------------------------|
| base_fee_per_gas   | bigint    | This block's base fee (introduced by [EIP1559](https://eips.ethereum.org/EIPS/eip-1559)) |
| difficulty         | bigint    | The effort required to mine the block                                                    |
| extra_data         | varchar   |                                                                                          |
| gas_limit          | bigint    | The gas limit of the current block                                                       |
| gas_used           | bigint    | The gas used in this block                                                               |
| hash               | varchar   | A unique identifier for that block                                                       |
| logs_bloom         | varchar   |                                                                                          |
| miner              | varchar   | The address of the miner                                                                 |
| nonce              | varchar   | The block nonce is used to demonstrate the proof of work during mining                   |
| number             | bigint    | The length of the blockchain in blocks                                                   |
| parent_hash        | varchar   | The unique identifier for the prior block                                                |
| receipts_root      | varchar   |                                                                                          |
| sha3_uncles        | varchar   |                                                                                          |
| size               | bigint    | This block's size in bytes (limited by gas limit)                                        |
| state_root         | varchar   |                                                                                          |
| timestamp          | bigint    |                                                                                          |
| total_difficulty   | bigint    | Total difficulty of the chain until this block                                           |
| transactions_root  | varchar   |                                                                                          |
| transactions_count | bigint    |                                                                                          |

## Transactions

Transactions are cryptographically signed instructions from accounts. An account will initiate a transaction to update the state of the Ethereum network. Transactions will always originate from externally owned accounts, a smart contract can not initiate a transaction.

Transactions need to be broadcast to the whole network. Any node can broadcast a request for a transaction to be executed on the EVM; after this happens, a miner will execute the transaction and propagate the resulting state change to the rest of the network.

Read more in the official Ethereum documentation [here](https://ethereum.org/en/developers/docs/transactions).

| Column                   | Data type | Description                                                                                                                                                                                 |
|--------------------------|-----------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| block_hash               | varchar   | A unique identifier for that block                                                                                                                                                          |
| block_number             | bigint    | The length of the blockchain in blocks                                                                                                                                                      |
| block_timestamp          | bigint    |                                                                                                                                                                                             |
| from_address             | varchar   | Address of the sender                                                                                                                                                                       |
| gas                      | bigint    | The gas consumed by the transaction in `wei`                                                                                                                                                |
| gas_price                | bigint    | The gas price in `wei`                                                                                                                                                                      |
| hash                     | varchar   | A unique identifier for that block                                                                                                                                                          |
| input                    | varchar   |                                                                                                                                                                                             |
| max_fee_per_gas          | bigint    | The maximum fee per gas the transaction sender is willing to pay total (introduced by [EIP1559](https://eips.ethereum.org/EIPS/eip-1559))                                                   |
| max_priority_fee_per_gas | bigint    | Maximum fee per gas the transaction sender is willing to give to miners to incentivize them to include their transaction (introduced by [EIP1559](https://eips.ethereum.org/EIPS/eip-1559)) |
| nonce                    | varchar   | The transaction nonce, unique to that wallet                                                                                                                                                |
| to_address               | varchar   | Address of the receiver. `null` when its a contract creation transaction                                                                                                                    |
| transaction_index        | bigint    | The transactions index position in the block                                                                                                                                                |
| transaction_type         | bigint    | The type of the transaction: `Legacy`, `AccessList`, or `DynamicFee`                                                                                                                        |
| value                    | bigint    | The amount of `[chain_gas_token]` sent in this transaction in `wei`. Note that ERC20 tokens do not show up here                                                                             |

## Receipts

**Coming soon**

## Logs

Event Logs tables store all logs data that gets generated by smart contracts.

This can be useful for querying contracts that are not yet decoded or are not able to be decoded since the code of the smart contract is not public.

Logs are an elegant way to store tiny amounts of data on EVM blockchains for a small amount of gas. Specifically, event logs are useful to let other people know something has happened without them having to query contracts individually.

For more on this topic read [this article](https://medium.com/mycrypto/understanding-event-logs-on-the-ethereum-blockchain-f4ae7ba50378).

| Column name       | Data type | Description                                                                                                  |
|-------------------|-----------|--------------------------------------------------------------------------------------------------------------|
| address           | varchar   | The address of the contract that emitted the log                                                             |
| block_hash        | varchar   | A unique identifier for that block                                                                           |
| block_number      | bigint    | The length of the blockchain in blocks                                                                       |
| data              | varchar   | Unindexed data containing further information on the event                                                   |
| log_index         | bigint    | This logs index position in the block (cumulative amount of logs ordered by execution)                       |
| topics            | varchar   |                                                                                                              |
| transaction_hash  | varchar   | The transaction hash of the transaction that produced this log                                               |
| transaction_index | bigint    | The index position of the transaction in this block (cumulative amount of transactions ordered by execution) |

# Stacks

# Soroban (Stellar)

# Move based chains

## Aptos derived

## Sui derived