---
title: "API"
format:
  html:
    toc: true
    html-math-method: katex
---
# Overview
Welcome to the Ortege Lakehouse API documentation. Our APIs offer seamless, secure, and efficient access to the Ortege Lakehouse, empowering you to run SQL queries against a vast, curated dataset tailored to meet the evolving needs of your projects. This documentation is designed to guide you through using our APIs to access and manipulate data within the Ortege Lakehouse, ensuring you can harness the full potential of our platform to drive insights and innovation.

# Features
* **Customizable Data Access:** Tailor your data queries to meet the specific needs of your project, with the flexibility to access as much or as little data as required.
* **Secure Authentication:** Connect to our APIs using a secure access key, ensuring your data queries and transfers are protected at every step.
* **Scalable Solutions**: Our infrastructure is designed to scale with your needs, from small-scale data exploration to enterprise-level data processing.
* **Real-time Insights**: Run SQL queries in real-time to gain immediate insights from the latest data available in the Ortege Lakehouse.

# Getting Started
## Authentication
To begin using the Ortege Lakehouse APIs, you'll need an API access key. Please reach out to [Support](mailto:abdullah@ortege.io) in order to obtain an API key.

Once you have your access key, you're ready to make your first API call. Here's a simple example to get you started:

```bash
curl --location 'https://adb-6741955360293064.4.azuredatabricks.net/api/2.0/sql/statements/' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer YOUR_ACCESS_KEY' \
--data '{
  "warehouse_id": "e6dba8cfba439486",
  "catalog": "external",
  "statement": "select * FROM db_pricing.tbl_prod_br_prices WHERE symbol = '\''STX'\'' LIMIT 10"
}'
```

Replace `YOUR_ACCESS_KEY` with your actual access key and your_dataset with the dataset you wish to query.

**PLEASE NOTE** Currently we don't rate limit API responses and as such some of the queries could return over a billion rows. Please always include LIMITs in your SQL queries. Our monitoring systems will know if you go over our limits and your API key may be revoked. 


# Best Practices
* **Secure Your API Key:** Treat your API key as you would a password. Do not share it or expose it in client-side code.
* **Optimize Queries:** To ensure efficient use of resources, optimize your SQL queries before execution.
* **Monitor Usage**: Keep an eye on your API usage to ensure it aligns with your project's needs and adjust as necessary.

# If You Get Stuck
While we strive to make Ortege Studio intuitive and easy to navigate, we understand that you may occasionally need a helping hand. If you find yourself facing difficulties, our dedicated support community on Discord is ready to assist you.

Visit our Discord server at https://discord.gg/ortege and join a network of fellow Ortege Studio users and experts. This vibrant community is a great place to find answers, share experiences, and collaborate on solutions.

**Open a Support Ticket**
Once you’re part of our Discord server, you can open a support ticket by navigating to the `#account-support` channel. Here’s how:

* Locate the `#account-support` channel in the channel list.
* Click the `Create ticket` button to create a new ticket.
* Provide a clear and concise description of the issue you're facing.

After submitting your ticket, a member of our support team will reach out to you. Response times may vary, but we’re committed to helping you resolve your issue as quickly as possible.