---
title: "Bronze Layer"
format:
  html:
    toc: true
    html-math-method: katex
---
The Bronze Layer acts as the primary reservoir for raw data from varied sources. This layer serves as the initial platform for data analysis and processing within the Ortege ecosystem. 

# Pricing 
**db_pricing**
Our pricing table currently gets aggregated pricing every 4 hours and not in realtime.

## Prices
**tbl_prod_br_prices**
This dataset includes various metrics such as supply details, current price, market capitalization, and price change percentages over different time frames. It also contains a timestamp indicating when the data was recorded or updated. 

| Column Name          | Type          | Description                                                                                      |
|----------------------|---------------|--------------------------------------------------------------------------------------------------|
| id_cmc               | Integer       | Unique identifier for the [CoinMarketCap](https://coinmarketcap.com/)                            |
| source               | string        | Source of where the pricing information is coming from                                           |
| name                 | String        | The full name of the cryptocurrency.                                                             |
| symbol               | String        | The abbreviated symbol or ticker used to represent the cryptocurrency.                           |
| circulating_supply   | Decimal/Double| The amount of cryptocurrency that is currently circulating in the market and publicly available. |
| total_supply         | Decimal/Double| The total amount of cryptocurrency that exists right now (minus any coins that have been verifiably burned).|
| price                | Decimal/Double| The current price of the cryptocurrency.                                                         |
| market_cap           | Decimal/Double| The total market value of the cryptocurrency's circulating supply.                               |
| percent_change_1h    | Decimal/Double| The percentage change in price over the last hour.                                               |
| percent_change_24h   | Decimal/Double| The percentage change in price over the last 24 hours.                                           |
| percent_change_7d    | Decimal/Double| The percentage change in price over the last 7 days.                                             |
| percent_change_30d   | Decimal/Double| The percentage change in price over the last 30 days.                                            |
| volume_24h           | Decimal/Double| The total trading volume of the cryptocurrency over the last 24 hours.                           |
| timestamp            | Timestamp     | The date and time at which the record was updated.                                               |

# Bitcoin 
**db_btc**

## Blocks
**tbl_prod_br_blocks**
This table encapsulates comprehensive details on Bitcoin blocks, encompassing mining data, block identification, and transaction specifics. It records the difficulty level, mining rewards, the unique hash identifying each block, its position within the blockchain, and the Merkle root for transaction integrity verification. Additionally, it includes metrics such as the block's size, the total number of transactions it contains, and the cumulative work or "chainwork" up to that point, expressed in hexadecimal. This table not only provides insights into the mining process, including the nonce and the compact target "bits," but also captures the economic aspects of mining through fields like mint reward, total fees, and the overall reward. The tbl_dev_br_blocks serves as a pivotal resource for analyzing the blockchain’s structural and economic dynamics, offering a granular view of each block's contribution to the ledger.

| col_name            | data_type | comment                                                                 |
|---------------------|-----------|-------------------------------------------------------------------------|
| bits                | string    | The encoded form of the target threshold this block’s header hash must be less than or equal to. |
| chainwork           | string    | The total amount of work done on this block’s chain, in hexadecimal.    |
| coinbase            | string    | The transaction containing the miner’s reward and any fees paid by transactions included in this block. |
| date                | string    | The date and time when this block was mined.                            |
| difficulty          | string    | The difficulty target for this block.                                   |
| hash                | string    | The hash of this block’s header.                                        |
| height              | bigint    | The height of this block in the blockchain.                             |
| merkle_root         | string    | The Merkle root of the transactions included in this block.             |
| mint_reward         | double    | The total amount of new bitcoins generated by mining this block.        |
| nonce               | string    | A random number used to try to find a valid block hash.                 |
| previous_block_hash | string    | The hash of the previous block in the blockchain.                       |
| size                | bigint    | The size of this block in bytes.                                        |
| stripped_size       | bigint    | The size of this block without witness data in bytes.                   |
| time                | timestamp | The Unix timestamp when this block was mined.                           |
| total_fees          | double    | The total amount of fees paid by transactions included in this block.   |
| total_reward        | double    | The total amount of bitcoins generated by mining this block, including both the mint reward and transaction fees. |
| transaction_count   | bigint    | The number of transactions included in this block.                      |
| weight              | bigint    | The weight of this block, used to calculate transaction fees.           |

## Transactions
**tbl_prod_br_transactions**
This table provides a detailed ledger of transactions within the Bitcoin chain, capturing both the technical aspects and the economic activities of each transaction. It records the transaction's metadata, such as its unique identifier (id), the block_hash it belongs to, its block_height and timing (block_date and block_time), and its placement within the block (index). The table delves into the composition of transactions, detailing the number and total value of inputs (input_count and input_value) and outputs (output_count and output_value), alongside arrays of input and output objects for granular transaction analysis. It also highlights whether a transaction is a coinbase transaction, indicating a miner's reward (is_coinbase), the transaction fees involved (fee), and technical parameters like hex representation, lock_time, size, version, and virtual_size. This comprehensive transactional overview aids in understanding the flow of bitcoins, transaction costs, and the operational dynamics of the Bitcoin blockchain.

| col_name        | data_type | comment                                                                                       |
|-----------------|-----------|-----------------------------------------------------------------------------------------------|
| block_date      | date      | The date when the block was added to the blockchain                                           |
| block_hash      | string    | The unique identifier of the block                                                            |
| block_height    | bigint    | The height of the block in the blockchain                                                     |
| block_time      | timestamp | The time when the block was added to the blockchain                                           |
| coinbase        | string    | The address that received the block reward for mining the block                               |
| fee             | bigint    | The transaction fee paid by the sender                                                        |
| hex             | string    | The hexadecimal representation of the transaction                                             |
| id              | string    | The unique identifier of the transaction                                                      |
| index           | bigint    | The index of the transaction in the block                                                     |
| input_count     | bigint    | The number of inputs in the transaction                                                       |
| input_value     | bigint    | The total value of all inputs in the transaction                                              |
| inputs          | array     | An array of input objects containing information about each input in the transaction          |
| is_coinbase     | boolean   | A boolean indicating whether the transaction is a coinbase transaction                        |
| lock_time       | bigint    | The lock time of the transaction                                                              |
| output_count    | bigint    | The number of outputs in the transaction                                                      |
| output_value    | bigint    | The total value of all outputs in the transaction                                             |
| outputs         | array     | An array of output objects containing information about each output in the transaction        |
| size            | bigint    | The size of the transaction in bytes                                                          |
| version         | bigint    | The version number of the transaction                                                         |
| virtual_size    | bigint    | The virtual size of the transaction                                                           |

# Stacks 
**db_stacks**

## Cycles
**tbl_prod_br_cycles**

The `tbl_prod_br_cycles` table provides a structured overview of cycles within the Stacks blockchain, starting from the genesis of Stacks 2.0. Each cycle represents a fixed number of blocks, facilitating the organization and analysis of blockchain data over time. This table is essential for understanding the temporal division of blockchain activity and aids in analyzing trends, rewards distributions, and other cycle-based metrics.

| Column       | Description                                       |
|--------------|---------------------------------------------------|
| `cycle`      | The sequential number of the cycle, starting from 0. Each cycle represents a group of 2100 blocks within the Stacks blockchain. |
| `start_block`| The starting block number for the given cycle. This marks the first block in the cycle. |
| `end_block`  | The ending block number for the given cycle. This marks the last block in the cycle. |
| `start_date`  | The start date for the given cycle. This marks the start of the cycle. |
| `end_date`  | The ending date for the given cycle. This marks the end of the cycle. |


## Blocks
**tbl_prod_br_blocks**
The table archives block data for the Stacks blockchain, detailing block identification, sequencing, and associated Bitcoin blockchain references due to Stacks' unique proof-of-burn consensus mechanism. It records block numbers, hashes, transaction counts, and the execution costs related to transactions, offering essential insights for analysis of network activity and transactional efficiency on the Stacks blockchain.

| col_name                  | data_type | comment                                                                                                                                                                                                                       |
|---------------------------|-----------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| canonical                 | boolean   | Canonical Blocks are the building blocks that contribute to the continuous, unbroken chain of blocks in the blockchain, each linking to its predecessor, forming the indelible ledger that blockchain is celebrated for. You expect this to be true. |
| number                    | bigint    | stacks block number                                                                                                                                                                                                           |
| hash                      | string    | A unique identifier for each block, generated by applying a cryptographic hash function to the block's data                                                                                                                   |
| index_block_hash          | string    | The hash of the index block.                                                                                                                                                                                                  |
| parent_block_hash         | string    | The hash of the parent block.                                                                                                                                                                                                 |
| timestamp                 | bigint    | Timestamp of relevant block. If you use `to_timestamp(timestamp)` SQL code, you will get the actual date-time.                                                                                                                |
| burn_block_hash           | string    | Corresponding Bitcoin block number's hash. The block that is written in Bitcoin block's hash.                                                                                                                                 |
| burn_block_height         | bigint    | Corresponding Bitcoin block number. The block that is written in a Bitcoin block.                                                                                                                                             |
| miner_txid                | string    | Corresponding transaction burned on Bitcoin block for the stacks block. Every stacks block is a transaction on Bitcoin. And this is that tx's id. If you remove the `0x` from the beginning, you will get the Bitcoin tx id. |
| transaction_count         | bigint    | Count of each transaction in the relevant block.                                                                                                                                                                              |
| execution_cost_read_count | bigint    | Captures the number of independent reads performed on the underlying data store.                                                                                                                                              |
| execution_cost_read_length| bigint    | The number of bytes read from the underlying data store.                                                                                                                                                                      |
| execution_cost_runtime    | bigint    | Captures the number of cycles that a single processor would require to process the Clarity block. This is a unitless metric, meant to provide a basis for comparison between different Clarity code blocks.                   |
| execution_cost_write_count| bigint    | Captures the number of independent writes performed on the underlying data store (see SIP-004).                                                                                                                               |
| execution_cost_write_length| bigint   | The number of bytes written to the underlying data store.                                                                                                                                                                     |

## Transactions
**tbl_prod_br_transactions**
The table is a comprehensive record of transactions on the Stacks blockchain. It includes transaction identifiers, sender information, execution costs, and status details. This table links transactions to blocks, tracks microblock inclusion, and categorizes transaction types, such as token transfers and smart contract executions. It's a key resource for analyzing transactional data within the Stacks ecosystem.

| col_name                  | data_type            | comment                                                                                                                                                 |
|---------------------------|----------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------|
| hash                      | string               | Unique identifier for the transaction                                                                                                                   |
| nonce                     | bigint               | Random number used in mining process                                                                                                                    |
| fee_rate                  | string               | Fee rate for the transaction                                                                                                                            |
| sender_address            | string               | Address of the sender                                                                                                                                   |
| sponsored                 | boolean              | Boolean indicating if the transaction is sponsored                                                                                                      |
| post_condition_mode       | string               | Mode for post-conditions                                                                                                                                |
| post_conditions           | array<struct>        | Array of post-conditions                                                                                                                                |
| anchor_mode               | string               | Mode for anchoring                                                                                                                                      |
| is_unanchored             | boolean              | Boolean indicating if the transaction is unanchored                                                                                                     |
| parent_block_hash         | string               | Hash of the parent block                                                                                                                                |
| block_hash                | string               | Hash of the block containing the transaction                                                                                                            |
| block_number              | bigint               | Block number containing the transaction                                                                                                                 |
| block_timestamp           | bigint               | Unix timestamp of the block containing the transaction                                                                                                       |
| parent_burn_block_time    | bigint               | Timestamp of the parent burn block                                                                                                                      |
| canonical                 | boolean              | Boolean indicating if the block is canonical                                                                                                            |
| tx_index                  | bigint               | Index of the transaction within the block                                                                                                               |
| tx_status                 | string               | Status of the transaction                                                                                                                               |
| tx_result                 | struct               | Result of the transaction                                                                                                                               |
| microblock_hash           | string               | Hash of the microblock containing the transaction                                                                                                       |
| microblock_sequence       | bigint               | Sequence number of the microblock containing the transaction                                                                                            |
| microblock_canonical      | boolean              | Boolean indicating if the microblock is canonical (Field marked as 'null' suggests missing information or not applicable.)                              |
| event_count               | bigint               | Count of events (Field marked as 'null' suggests missing information or not applicable.)                                                                |
| events                    | array<struct>        | Array of events (Field marked as 'null' suggests missing information or not applicable.)                                                                |
| execution_cost_read_count | bigint               | Number of independent reads performed on the underlying data store (Field marked as 'null' suggests missing information or not applicable.)             |
| execution_cost_read_length| bigint               | Number of bytes read from the underlying data store (Field marked as 'null' suggests missing information or not applicable.)                            |
| execution_cost_runtime    | bigint               | Number of cycles for processing (Field marked as 'null' suggests missing information or not applicable.)                                               |
| execution_cost_write_count| bigint               | Number of independent writes performed on the underlying data store (Field marked as 'null' suggests missing information or not applicable.)           |
| execution_cost_write_length| bigint             | Number of bytes written to the underlying data store (Field marked as 'null' suggests missing information or not applicable.)                          |
| tx_type                   | string               | Type of the transaction (Field marked as 'null' suggests missing information or not applicable.)                                                       |
| token_transfer            | struct               | Details of token transfer if applicable (Field marked as 'null' suggests missing information or not applicable.)                                       |
| coinbase_payload          | struct               | Data for coinbase transactions (Field marked as 'null' suggests missing information or not applicable.)                                                |
| smart_contract            | struct               | Details of the smart contract if applicable (Field marked as 'null' suggests missing information or not applicable.)                                   |
| contract_call             | struct               | Details of the contract call if applicable (Field marked as 'null' suggests missing information or not applicable.)                                    |
| poison_microblock         | map<string,string>   | Information on poisoned microblock if applicable (Field marked as 'null' suggests missing information or not applicable.)                              |


## Contracts
**tbl_prod_br_contracts**
The table records details of smart contracts on the Stacks blockchain. It tracks the transaction hash (tx_hash), whether the contract is the main (canonical) version, the contract's address, and the associated block number. Contract-specific data like Clarity language version (clarity_version), source code, and ABI (Application Binary Interface) are also stored. Additionally, flags indicate if the contract pertains to a STX20 token (is_stx20) or a non-fungible token (is_nft), offering insights into the contract's purpose and functionality. This table is vital for developers and analysts interested in smart contract deployment and usage patterns on Stacks.

| col_name         | data_type | comment                                                                                                                                                                                                                     |
|------------------|-----------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| tx_hash          | string    | Transaction hash of the contract. Try searching it in explorer.hiro.so                                                                                                                                                     |
| canonical        | boolean   | Canonical Blocks are the building blocks that contribute to the continuous, unbroken chain of blocks in the blockchain, each linking to its predecessor, forming the indelible ledger that blockchain is celebrated for. You expect this to be true. |
| address          | string    | Address of the contract.                                                                                                                                                                                                    |
| block_number     | bigint    | In which block this contract recorded in.                                                                                                                                                                                   |
| clarity_version  | bigint    | Clarity version of the contract.                                                                                                                                                                                            |
| source_code      | string    | The source code of the contract.                                                                                                                                                                                            |
| abi              | string    | The ABI (Application Binary Interface) of the contract.                                                                                                                                                                     |
| is_stx20         | boolean   | Indicates whether the contract is a Stacks 2.0 token (STX20).                                                                                                                                                               |
| is_nft           | boolean   | Indicates whether the contract is a non-fungible token (NFT).                                                                                                                                                               |
# Stellar
**db_soroban**

## Ledger
**tbl_test_br_ledgers**

The `tbl_test_br_ledgers` table holds essential data for each ledger within the Stellar blockchain. It contains ledger identifiers, hash information, timestamps, and detailed transaction metrics. This data is crucial for understanding ledger changes, transaction dynamics, and overall blockchain activity on the Stellar network.

| Column Name                | Data Type | Description                                                                                                             |
|----------------------------|-----------|-------------------------------------------------------------------------------------------------------------------------|
| `id`                       | Integer   | The unique identifier for the ledger.                                                                                   |
| `sequence`                 | Integer   | The sequence number of the ledger, indicating its position in the Stellar blockchain.                                   |
| `hash`                     | String    | The hash of the ledger, serving as a cryptographic signature.                                                           |
| `prev_hash`                | String    | The hash of the previous ledger, linking the current ledger to its predecessor.                                         |
| `timestamp`                | Timestamp | The timestamp of when the ledger was created.                                                                           |
| `closed_at`                | Timestamp | The time when the ledger was closed and finalized.                                                                      |
| `total_coins`              | String    | The total number of coins within the ledger.                                                                            |
| `fee_pool`                 | String    | The pool of fees accumulated from transaction costs within the ledger.                                                  |
| `base_fee_in_stroops`      | Integer   | The base fee (in stroops, the smallest unit of the Stellar cryptocurrency) for transactions within the ledger.          |
| `base_reserve_in_stroops`  | Integer   | The base reserve (in stroops) required to be held in each account on the Stellar network.                               |
| `max_tx_set_size`          | Integer   | The maximum number of transactions that can be included in a transaction set for this ledger.                           |
| `protocol_version`         | Integer   | The version of the Stellar protocol with which the ledger complies.                                                     |
| `header_xdr`               | String    | The XDR (External Data Representation) format of the ledger header.                                                     |
| `paging_token`             | String    | A token used for paging through results.                                                                                |
| `successful_transaction_count` | Integer | The number of transactions that were successfully processed in the ledger.                                           |
| `failed_transaction_count` | Integer   | The number of transactions that failed processing in the ledger.                                                        |
| `operation_count`          | Integer   | The total number of operations within all transactions in the ledger.                                                   |
| `tx_set_operation_count`   | Integer   | The total number of operations within the transaction set for this ledger.                                              |


## Transactions
**tbl_test_br_transactions**

This table catalogs the individual transactions on the Stellar blockchain, capturing the essence of each financial event. Each entry includes the transaction's unique identifier, its status, the associated ledger number, and precise timing information. It details the transaction fee, operation count, and the XDR (External Data Representation) information for envelopes, results, and fee meta, which encapsulates the transaction in a standardized format for interoperability. Furthermore, the table stores memo-related data, crucial for transaction annotation, along with a count and array of signatures verifying the transaction. This dataset is invaluable for tracing Stellar transactions, understanding fee structures, and examining transactional metadata for analysis and verification.

| Column Name           | Type        | Description                                                        |
|-----------------------|-------------|--------------------------------------------------------------------|
| id                    | Integer     | Unique identifier for the transaction.                             |
| paging_token          | String      | A cursor value used for paginating through transaction records.    |
| successful            | Boolean     | Indicates whether the transaction was successful.                  |
| hash                  | String      | The unique hash of the transaction.                                |
| ledger                | Integer     | The ledger number that the transaction was included in.            |
| timestamp             | Timestamp   | The date and time at which the transaction occurred.               |
| created_at            | Timestamp   | The date and time when the transaction was created.                |
| source_account        | String      | The initiating account of the transaction.                         |
| source_account_sequence| Long       | The sequence number of the source account.                        |
| fee_account           | String      | The account charged for the transaction fee.                       |
| fee_charged           | Long        | The fee amount charged for the transaction.                        |
| max_fee               | Long        | The maximum fee the source account is willing to pay.              |
| operation_count       | Integer     | The number of operations included in the transaction.              |
| envelope_xdr          | String      | The transaction envelope in XDR format.                            |
| result_xdr            | String      | The result of the transaction in XDR format.                       |
| result_meta_xdr       | String      | Additional result details in XDR format.                           |
| fee_meta_xdr          | String      | Fee-related metadata in XDR format.                                |
| memo_type             | String      | Type of memo included with the transaction.                        |
| memo                  | String      | Memo value included with the transaction.                          |
| memo_bytes            | Blob        | Memo value in bytes, for binary memos.                             |
| signatures            | Struct      | Struct of signatures confirming the transaction's validity.        |
| valid_after           | Timestamp   | The time after which the transaction is valid.                     |
| valid_before          | Timestamp   | The time before which the transaction is valid.                    |
| preconditions              | Struct      | Details of preconditions necessary for the transaction. Includes `timebounds`, `ledgerbounds`, `min_account_sequence`, `min_account_sequence_age`, `min_account_sequence_ledger_gap`, and `extra_signers`. |
| fee_meta                   | Struct      | Metadata related to the transaction fee structure. Includes `fee_source`, `fee`, `inner_tx`, and `ext`.                                        |
| result                     | Struct      | Outcome details of the transaction processing. Includes `fee_charged`, `result`, and `ext`.                                                   |
| envelope                   | Struct      | Contains the transaction payload and authorization data. Includes `type`, `v1`, `fee_bump`, `tx`, and `signatures`.                            |

## Events
**tbl_test_br_events**
The `tbl_test_br_events` table captures key event data within the Stellar blockchain. Each event is tied to a ledger and transaction, providing a detailed account of contract calls and operations. It includes event types, ledger closure times, contract identifiers, and transaction hashes. Notable is the inclusion of a 'paging_token' which allows for consistent querying within paginated results. The table is pivotal for tracking the execution and outcomes of contract calls, offering a granular view of the events that occur within the Stellar ecosystem.

| Column Name             | Type        | Description |
|-------------------------|-------------|-------------|
| event_type              | String      | The type of event, such as a contract call or operation executed within the ledger. |
| ledger                  | Integer     | The sequence number of the ledger where the event occurred. |
| ledger_closed_at        | Timestamp   | The time when the ledger containing the event was closed and finalized. |
| contract_id             | String      | The unique identifier for the contract involved in the event. |
| tx_hash                 | String      | The hash of the transaction associated with the event. |
| id                      | String      | The unique identifier for the event. |
| paging_token            | String      | A token used for paginating through a set of results. |
| in_successful_contract_call | Boolean | Indicates whether the event was part of a successful contract call. |
| topic                   | Array       | Contains `items` with event-specific information, and `value` to describe the event details. |



# Address book 
**db_address_book**
Ortege Lakehouse distinguishes itself with a dedicated address book database that consolidates wallet addresses across various blockchains into a single unified repository. This unique design supports ML and AI-driven cross-chain analytics, enabling a comprehensive understanding and deeper insights into the entire crypto ecosystem from one source of truth.

## General
These tables cover addresses across multiple blockchains and aren't blockchain specific

### tbl_test_br_address_labels
Classifies blockchain addresses based on their associated activities. Currently, this table includes Bitcoin addresses known for participating in Stacks (STX) token stacking. This table allows users to quickly identify and analyze addresses that are active in specific blockchain operations.

| Column Name | Type    | Description                                              |
|-------------|---------|----------------------------------------------------------|
| address     | String  | The unique identifier for a wallet on the blockchain.     |
| blockchain  | String  | The name of the blockchain network, e.g., 'bitcoin'.      |
| label       | String  | A descriptive label for the address, e.g., 'STX stacker'. |

## Bitcoin
**db_btc**
These tables specifically focus on Bitcoin and interesting wallets in the Bitcoin ecosystem

### Wallet first seen (tbl_test__br_address_bitcoin_first_seen)
This table returns all wallets on Bitcoin as well as the date the address was first seen

### Wallet size (tbl_test_br_bitcoin_wallet_size)
This table classifies all Bitcoin addresses by their BTC holdings. We classify wallets as:

* < 1 BTC Shrimp
* Between 1 BTC and < 10 BTC Crap
* Between 10 BTC and < 100 BTC Fish
* Between 100 BTC and < 1K BTC Shark
* Between 1K BTC and < 10k BTC Whale
* More than 10k BTC Mega Whale
