on:
  workflow_dispatch:
  push:
    branches: ["main"]

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # this we only want to run if event is push
      # quarto publish action automatically removes all extra files
      # so its removing CNAME which is for custom domain for github pages
      - name: Create & Push CNAME file
        if: github.event_name == 'push'
        run: |
          git fetch
          git checkout gh-pages
          git pull origin gh-pages
          echo "docs.ortege.ai" > CNAME
          git add CNAME
          git commit -m "Create CNMAE"
          git push origin gh-pages
